# Generated by Django 2.2.7 on 2019-12-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20191222_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('subheading', models.CharField(max_length=300)),
                ('meta', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('pages', models.IntegerField(choices=[(0, '/'), (1, '/blog'), (2, '/about'), (3, '/contact')], default=0)),
            ],
        ),
    ]
