# Generated by Django 2.2.7 on 2019-12-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='page',
            name='subheading',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
