# Generated by Django 2.2.7 on 2019-12-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20191222_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
