# Generated by Django 2.2.7 on 2019-12-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('page', models.CharField(max_length=300)),
                ('heading', models.CharField(max_length=300)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('meta', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
