# Generated by Django 2.2.7 on 2019-12-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_photo',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
