# Generated by Django 2.2.7 on 2019-12-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_page_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
        migrations.AlterField(
            model_name='page',
            name='heading',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
